# Generated by Django 3.2.4 on 2022-09-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='mcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=70)),
                ('pid', models.IntegerField()),
                ('cdate', models.DateField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='morder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=70)),
                ('pid', models.IntegerField()),
                ('remarks', models.CharField(max_length=20)),
                ('odate', models.DateField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
