# Generated by Django 3.2.4 on 2022-09-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_mcart_morder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcart',
            name='cdate',
            field=models.CharField(max_length=100),
        ),
    ]
